### PR TITLE
Adding more TIDs for event series images to display

### PR DESCRIPTION
**Pull request by crawleyde**
As per #10.

### CODE REVIEW

**Comment by crawleyde** [comment]
@davekisly can you give this a quick eyeball? Thanks.

**Comment by davekisly** [comment]
Looking only at the snippet (https://github.com/OPLBPO/opl_field_formatters/pull/11/files), i can't tell what $items[$id] is supposed to do (or where $id is set). So, i can't give u an immediate yah or nay on this. Give me a couple minutes to look at the code.

**Comment by davekisly** [comment]
I'll probably need to check this branch out. Or, do you have this running on one of the DEV sites? Are there specific nodes i can look at to review?

**Comment by crawleyde** [comment]
If you can check out the branch locally, the operative events are those in the TD Summer Reading Club series, which should display the associated taxonomy image from the Series vocabulary. I needed to adjust permissions on my local image preset folder again to have them show up.

**Comment by davekisly** [comment]
I might need to refresh my local DB to test (or as you suggest, update my folder permissions, but those seem ok to my eye). In any case, looking again at the lines in question, the new code `if (in_array($series_ex->tid, array('1554', '1563'))) {` seems fine. Go ahead and commit if its not throwing errors on your local.

**Comment by crawleyde** [comment]
OK, thanks.

**Pull request merged**
